# Nombre de la aplicación
spring.application.name=gestion-talleres


# Configuración de la Base de Datos
spring.datasource.url=jdbc:mysql://localhost:3306/gestion_talleres
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# JPA / Hibernate
# 'update' creará las tablas automáticamente según las clases @Entity
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


# Seguridad y JWT
# Recuerda que en producción esta clave debe ser mucho más compleja
jwt.secret=${JWT_SECRET:EstaEsMiClaveSecretaParaGestionDeTalleres2026}
jwt.expiration=86400000


# Puerto del servidor
server.port=8080


# Configuración de subida de archivos (Útil para subir fotos de los talleres o folletos)
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB


# Logs
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE



