# ==========================================
# CONFIGURACIÓN DE LA APLICACIÓN
# ==========================================
spring.application.name=gestion-talleres
server.port=8080
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true

# ------------------------------------------
# OPCIÓN A: H2 - BASE DE DATOS EN MEMORIA
# ------------------------------------------
# spring.datasource.url=jdbc:h2:mem:gestion_talleres;DB_CLOSE_DELAY=-1;CASE_INSENSITIVE_IDENTIFIERS=TRUE
# spring.datasource.username=sa
# spring.datasource.password=
# spring.datasource.driver-class-name=org.h2.Driver
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console

# ------------------------------------------
# OPCIÓN B: MYSQL - BASE DE DATOS LOCAL
# ------------------------------------------
spring.datasource.url=jdbc:mysql://localhost:3306/gestion_talleres?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ==========================================
# JPA / HIBERNATE
# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# CAMBIA ESTO: 'always' para que ejecute tus INSERTS al arrancar
spring.sql.init.mode=never

# AÑADE ESTO: obliga a que primero se creen las tablas y LUEGO se metan los datos
spring.jpa.defer-datasource-initialization=true

# ==========================================
# SEGURIDAD Y ARCHIVOS
# ==========================================
jwt.secret=${JWT_SECRET:EstaEsMiClaveSecretaParaGestionDeTalleres2026}
jwt.expiration=86400000

# Tamaño máximo de fotos para los talleres (2MB)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

logging.level.org.springframework.security=DEBUG

# ==========================================
# CONFIGURACIÓN DE CORREO (SMTP) 
# ==========================================
spring.mail.host=localhost
spring.mail.port=2525
spring.mail.username=696de23914b5ef
spring.mail.password=d52bc693f34b29
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# Modo debug para ver la conversación con el servidor en la consola
spring.mail.properties.mail.debug=true

# ==========================================
# CONFIGURACIÓN DE RUTAS DE ALMACENAMIENTO (LOCAL)
# ==========================================
# app.storage.public-path=../frontend/public
# app.storage.protected-path=storage

# Rutas de desarollo
app.storage.public-path=./frontend/public
app.storage.protected-path=./storage